resolver: nightly-2020-10-05

flags: {}
packages:
    - .
    - ./ipython-kernel
    - ./ghc-parser

ghc-options:
  ghc-parser: -Wall -Wpartial-fields -Werror
  ihaskell: -Wall -Wpartial-fields -Werror
